<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-10-12 19:42
=======
# Generated by Django 5.1.1 on 2024-10-07 15:31
>>>>>>> 43da4474253a6abb4f73cdfeedd758e8f1677323

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Metro',
            fields=[
                ('id_metro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metro', models.CharField(max_length=50)),
                ('linea_metro', models.IntegerField()),
                ('cantidad_aglomeracion', models.IntegerField(default=1000)),
=======
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
>>>>>>> 43da4474253a6abb4f73cdfeedd758e8f1677323
            ],
        ),
    ]
