# Generated by Django 5.1.1 on 2024-10-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='f_id_metro',
            field=models.ForeignKey(db_column='id_metro', on_delete=django.db.models.deletion.CASCADE, to='Metro.mantenedor_metro'),
        ),
        migrations.CreateModel(
            name='Mantenedor_bus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_personas', models.IntegerField()),
                ('f_id_metro', models.ForeignKey(db_column='id_metro', on_delete=django.db.models.deletion.CASCADE, to='Metro.mantenedor_metro')),
            ],
        ),
        migrations.AddField(
            model_name='reporte',
            name='f_id_bus',
            field=models.ForeignKey(db_column='id_bus', null=True, on_delete=django.db.models.deletion.CASCADE, to='Metro.mantenedor_bus'),
        ),
    ]
