# Generated by Django 5.1.1 on 2024-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metro', '0002_alter_mantenedor_metro_linea_metro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenedor_metro',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
