# Generated by Django 5.1.1 on 2024-10-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metro', '0002_alter_reporte_f_id_metro_mantenedor_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenedor_bus',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
