# Generated by Django 5.1.1 on 2024-10-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metro', '0003_mantenedor_bus_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
