# Generated by Django 5.1.1 on 2024-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Metro', '0004_alter_reporte_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenedor_bus',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mantenedor_metro',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
